/*
 * push_hook.c — LD_PRELOAD hook for Ableton Push 3's libusb calls
 *
 * Intercepts libusb_bulk_transfer / libusb_submit_transfer to:
 *   Phase 1: log display frames (ep 0x01) + MIDI traffic (ep 0x03/0x83)
 *   Phase 2: overlay / full frame takeover on the Push display
 *
 * Build:
 *   gcc -shared -fPIC -o push_hook.so push_hook.c -ldl -lpthread -O2
 *
 * Inject:
 *   export LD_PRELOAD=/data/push-hack/hacks/push-display/push_hook.so
 *   (add to /etc/init.d/push3 before start-stop-daemon line, restart push3)
 *
 * Display protocol (Push 3, confirmed empirically):
 *   endpoint:  0x01 (bulk OUT)
 *   header:    16 bytes — { 0xFF, 0xCC, 0xAA, 0x88, 0x00, ... }
 *   pixels:    BGR565 (16-bit LE: bits 15-11=B, 10-5=G, 4-0=R)
 *   shaping:   XOR with repeating {0xE7,0xF3,0xE7,0xFF} (phase-1 of 0xFFE7F3E7)
 *   Push 2/3:  960×160 px visible, stride 1024 px/row (64px padding)
 *              1024×160×2 = 327680 bytes per half-frame
 *              Push 3 sends each frame TWICE → 655360 bytes total
 *
 * Shared-memory control (with push-manager):
 *   file:  /data/push-hack/hacks/push-display/framebuf
 *   magic: 0x50555348 ("PUSH") at offset 0
 *   layout: { uint32 magic, uint32 version, uint32 mode, uint32 frame_seq,
 *             uint8 pixels[655360] }
 *   mode 0 = passthrough (Ableton UI untouched)
 *   mode 1 = bar overlay (orange test bar at top)
 *   mode 2 = full frame takeover (pixels[] painted over every frame)
 */

#include <dlfcn.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>

/* splash_data.h is generated by gen_splash/main.go — run `make splash` to regenerate. */
#include "splash_data.h"

/* Seconds to wait before falling back to passthrough if push-manager never connects. */
#define SPLASH_FALLBACK_SECS 10

/* Seconds after hook load during which the hook stays fully passive
 * (passthrough, no buffer mutation, no forced mode). This protects Push3's
 * one-time USB/hub bring-up window: taking over the display the instant the
 * hook loads was found to disturb the USB-A hub-port (1-1.2) power enable,
 * leaving the USB-A port dead until a hookless reboot. */
#define BOOT_GRACE_SECS 8

/* How long the boot splash is shown once the grace window has elapsed. */
#define SPLASH_SHOW_SECS 3

/* ── libusb type stubs (avoid header dependency) ─────────────────────────── */

typedef struct libusb_device_handle libusb_device_handle;

typedef int (*bulk_xfer_fn)(
    libusb_device_handle *dev_handle,
    unsigned char         endpoint,
    unsigned char        *data,
    int                   length,
    int                  *actual_length,
    unsigned int          timeout);

struct libusb_transfer {
    libusb_device_handle *dev_handle;
    uint8_t               flags;
    unsigned char         endpoint;
    unsigned char         type;
    unsigned int          timeout;
    int                   status;
    int                   length;
    int                   actual_length;
    void                 *callback;
    void                 *user_data;
    unsigned char        *buffer;
    int                   num_iso_packets;
};

typedef int (*submit_xfer_fn)(struct libusb_transfer *transfer);

/* snd_seq_event_input — use void* to avoid ALSA header dependency */
typedef int (*seq_event_input_fn)(void *seq, void **ev);

/* ── Shared memory control block ────────────────────────────────────────────
 *
 * Mmap'd from /data/push-hack/hacks/push-display/framebuf.
 * Created by this hook on first load; updated by push-manager.
 * ── */

#define SHM_MAGIC   0x50555348u   /* "PUSH" */
#define SHM_VERSION 1u

/* Display geometry (same protocol as Push 2, confirmed):
 *   visible pixels: 960×160
 *   row stride:     1024 pixels (64px padding per row)
 *   bytes per frame: 1024 × 160 × 2 = 327680
 *   Push 3 sends the frame TWICE per display update → 655360 bytes total */
#define DISPLAY_VIS_W    960          /* visible columns          */
#define DISPLAY_HEIGHT   160          /* rows                     */
#define DISPLAY_STRIDE   1024         /* pixels per row in buffer */
#define BYTES_PER_PIXEL  2
#define BYTES_PER_ROW    (DISPLAY_STRIDE * BYTES_PER_PIXEL)          /* 2048 */
#define FRAME_BYTES      (DISPLAY_STRIDE * DISPLAY_HEIGHT * BYTES_PER_PIXEL) /* 327680 */
#define TOTAL_BYTES      (FRAME_BYTES * 2)                           /* 655360 */

#define DISPLAY_MODE_PASS     0u  /* passthrough — Ableton UI shows normally */
#define DISPLAY_MODE_BAR      1u  /* orange bar overlay */
#define DISPLAY_MODE_TAKEOVER 2u  /* full frame replacement */

typedef struct __attribute__((packed)) {
    uint32_t magic;              /*  0: 0x50555348 */
    uint32_t version;            /*  4: 1          */
    uint32_t mode;               /*  8: 0/1/2      */
    uint32_t frame_seq;          /* 12: incremented by push-manager when new frame ready */
    uint8_t  pixels[TOTAL_BYTES];/* 16: raw BGR565, no XOR — hook applies XOR on copy   */
} push_display_shm_t;

#define SHM_FILE "/data/push-hack/hacks/push-display/framebuf"
#define SHM_SIZE sizeof(push_display_shm_t)  /* 16 + 655360 = 655376 bytes */

/* ── MIDI filter shared memory ──────────────────────────────────────────────
 *
 * Tiny (16-byte) shm file.  push-manager writes enabled=0/1;
 * this hook reads it before each snd_seq_event_input call.
 *
 * When enabled, performance events (Note On/Off, CC, etc.) delivered to
 * Push3's RtMidi loop have their type byte zeroed (SND_SEQ_EVENT_NONE=0).
 * RtMidi silently discards type-0 events → Live never sees the press.
 * SysEx and Active Sensing always pass through unchanged.
 * ── */

#define MIDI_FILT_FILE  "/data/push-hack/hacks/push-display/midiflt"
#define MIDI_FILT_MAGIC 0x4D464C54u  /* "MFLT" */

typedef struct __attribute__((packed)) {
    uint32_t magic;      /* 0x4D464C54 */
    uint8_t  enabled;    /* 0=passthrough, 1=filter active */
    uint8_t  _pad[11];   /* reserved for future per-channel / note-range flags */
} push_midi_filt_t;

/* ── Display overlay — orange bar ───────────────────────────────────────── */

#define BAR_Y   0    /* top row of bar */
#define BAR_H   20   /* height in rows */

/* Orange #FF5500 in BGR565 = 0x02BF; LE bytes: lo=0xBF hi=0x02 */
#define BAR_COLOR_LO  0xBF
#define BAR_COLOR_HI  0x02

/* ── State ───────────────────────────────────────────────────────────────── */

static bulk_xfer_fn        real_bulk      = NULL;
static submit_xfer_fn      real_submit    = NULL;
static seq_event_input_fn  real_seq_input = NULL;
static FILE               *log_fp         = NULL;
static push_display_shm_t *shm            = NULL;
static push_midi_filt_t   *midi_filt      = NULL;

static pthread_mutex_t log_mutex     = PTHREAD_MUTEX_INITIALIZER;
static pthread_mutex_t display_mutex = PTHREAD_MUTEX_INITIALIZER;

/* hook_active: 1 only in the Push3 display/MIDI process. In every other
 * push3 child (launcher, web service, …) the interposers fall straight
 * through to the real libusb/ALSA functions with zero side effects. */
static int    hook_active = 0;
/* Hook load time (seconds), for the BOOT_GRACE_SECS passive window. */
static time_t load_time   = 0;

static volatile int display_frames = 0;
static volatile int midi_out_msgs  = 0;
static volatile int midi_in_msgs   = 0;

/* Frame-tracking state (protected by display_mutex) */
static int pixel_byte_offset = 0;
static int in_pixel_frame    = 0;

/* ── BGR565 pixel helpers ─────────────────────────────────────────────────
 * XOR pattern confirmed: black pixels (0x0000) appear as e7 f3 e7 ff on wire.
 * This is phase-1 rotation of the 0xFFE7F3E7 value cited in Push 2 docs.
 * ──────────────────────────────────────────────────────────────────────── */

static const uint8_t XOR_PATTERN[4] = { 0xE7, 0xF3, 0xE7, 0xFF };

static uint16_t __attribute__((unused)) rgb_to_bgr565(uint8_t r, uint8_t g, uint8_t b) {
    return ((uint16_t)(b >> 3) << 11) |
           ((uint16_t)(g >> 2) << 5)  |
           ((uint16_t)(r >> 3));
}

/* ── Logging ─────────────────────────────────────────────────────────────── */

#define LOG_PATH     "/data/push-hack/logs/push-hook.log"
#define LOG_FALLBACK "/tmp/push-hook.log"

static void log_open(void) {
    if (log_fp) return;
    log_fp = fopen(LOG_PATH, "a");
    if (!log_fp) log_fp = fopen(LOG_FALLBACK, "a");
    if (log_fp) setbuf(log_fp, NULL);
}

static void hook_logf(const char *fmt, ...) {
    char buf[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    pthread_mutex_lock(&log_mutex);
    log_open();
    if (log_fp) fputs(buf, log_fp);
    else syslog(LOG_INFO, "push_hook: %s", buf);
    pthread_mutex_unlock(&log_mutex);
}

/* ── Startup splash ─────────────────────────────────────────────────────── */

/* Deferred boot splash.
 *
 * The hook loads at the very start of Push3, while the firmware is still
 * bringing up the XMOS and the internal USB hub. Taking over the display
 * immediately (heavy per-frame XOR rewrites under a mutex) disturbed that
 * bring-up and left the USB-A hub port dead. So the hook now stays passive
 * for BOOT_GRACE_SECS, then briefly shows the splash, then restores
 * passthrough — only if push-manager hasn't already taken the display. */
static void *splash_thread(void *arg) {
    push_display_shm_t *s = (push_display_shm_t *)arg;
    sleep(BOOT_GRACE_SECS);
    if (s->mode == DISPLAY_MODE_PASS) {
        s->mode = DISPLAY_MODE_TAKEOVER;
        hook_logf("splash: grace elapsed, showing splash (takeover)\n");
        sleep(SPLASH_SHOW_SECS);
        if (s->mode == DISPLAY_MODE_TAKEOVER) {
            s->mode = DISPLAY_MODE_PASS;
            hook_logf("splash: done, mode=passthrough\n");
        }
    }
    return NULL;
}

/* ── Shared memory init ─────────────────────────────────────────────────── */

static void shm_init(void) {
    int fd = open(SHM_FILE, O_RDWR | O_CREAT, 0664);
    if (fd < 0) {
        hook_logf("shm: open failed: %s\n", SHM_FILE);
        return;
    }

    /* Ensure file is large enough */
    struct stat st;
    if (fstat(fd, &st) == 0 && (size_t)st.st_size < SHM_SIZE) {
        if (ftruncate(fd, (off_t)SHM_SIZE) < 0) {
            hook_logf("shm: ftruncate failed\n");
            close(fd);
            return;
        }
    }

    /* Force world-writable so ableton (non-root) can mmap R/W even if root
     * created the file via start-stop-daemon constructor firing first. */
    fchmod(fd, 0666);

    void *m = mmap(NULL, SHM_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    close(fd);

    if (m == MAP_FAILED) {
        hook_logf("shm: mmap failed\n");
        return;
    }

    push_display_shm_t *s = (push_display_shm_t *)m;
    int first_init = (s->magic != SHM_MAGIC);

    if (first_init) {
        memset(s, 0, SHM_SIZE);
        s->magic   = SHM_MAGIC;
        s->version = SHM_VERSION;
    }

    /* Buffer the splash image but DO NOT take over the display yet. The hook
     * stays in passthrough during boot so it cannot disturb Push3's USB/hub
     * bring-up; the deferred splash_thread shows the splash after the grace
     * window. frame_seq is reset to 0 so push-manager can detect a fresh load. */
    memcpy(s->pixels, splash_pixels, sizeof(s->pixels));
    s->mode      = DISPLAY_MODE_PASS;
    s->frame_seq = 0;

    hook_logf("shm: %s at %s — splash buffered, mode=passthrough, frame_seq=0\n",
              first_init ? "initialized" : "re-attached", SHM_FILE);

    /* Deferred splash: wait out the boot grace window, then briefly show it. */
    pthread_t tid;
    pthread_create(&tid, NULL, splash_thread, (void *)s);
    pthread_detach(tid);

    shm = s;
}

/* ── MIDI filter shm init ────────────────────────────────────────────────── */

static void midi_filt_init(void) {
    int fd = open(MIDI_FILT_FILE, O_RDWR | O_CREAT, 0664);
    if (fd < 0) {
        hook_logf("midi_filt: open failed: %s\n", MIDI_FILT_FILE);
        return;
    }
    size_t sz = sizeof(push_midi_filt_t);
    struct stat st;
    if (fstat(fd, &st) == 0 && (size_t)st.st_size < sz) {
        if (ftruncate(fd, (off_t)sz) < 0) {
            hook_logf("midi_filt: ftruncate failed\n");
            close(fd);
            return;
        }
    }
    fchmod(fd, 0666);
    void *m = mmap(NULL, sz, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    close(fd);
    if (m == MAP_FAILED) {
        hook_logf("midi_filt: mmap failed\n");
        return;
    }
    push_midi_filt_t *f = (push_midi_filt_t *)m;
    if (f->magic != MIDI_FILT_MAGIC) {
        memset(f, 0, sz);
        f->magic   = MIDI_FILT_MAGIC;
        f->enabled = 0;
    }
    midi_filt = f;
    hook_logf("midi_filt: initialized at %s (enabled=%u)\n", MIDI_FILT_FILE, f->enabled);
}

/* ── Constructor: called when .so is loaded ──────────────────────────────── */

__attribute__((constructor))
static void hook_init(void) {
    load_time = time(NULL);
    real_bulk      = (bulk_xfer_fn)       dlsym(RTLD_NEXT, "libusb_bulk_transfer");
    real_submit    = (submit_xfer_fn)     dlsym(RTLD_NEXT, "libusb_submit_transfer");
    real_seq_input = (seq_event_input_fn) dlsym(RTLD_NEXT, "snd_seq_event_input");
    /* NB: do NOT openlog() here. Push3 uses --log-to-syslog, and calling
     * openlog() from this LD_PRELOAD constructor changes the syslog ident for
     * the whole process — re-tagging Push3's own messages as "push_hook:".
     * hook_logf()'s syslog fallback already prefixes "push_hook:" in the text
     * and syslog() opens with the default ident on first use, so identifiable
     * logging is preserved without hijacking Push3's identity. */

    /* Scope the hook to the Push3 display/MIDI process only. The init.d
     * LD_PRELOAD line is inherited by every push3 child (the Python launcher,
     * PushWebServiceCli, …). Running our shm/display/MIDI logic in those
     * processes is unnecessary and disturbs USB-A hub-port bring-up. Identify
     * the right process by name; elsewhere the interposers pass straight
     * through to the real functions. */
    char comm[64] = {0};
    int cfd = open("/proc/self/comm", O_RDONLY);
    if (cfd >= 0) {
        ssize_t n = read(cfd, comm, sizeof(comm) - 1);
        close(cfd);
        if (n > 0 && comm[n - 1] == '\n') comm[n - 1] = '\0';
    }
    hook_active = (strcmp(comm, "Push3") == 0);

    if (hook_active) {
        shm_init();
        midi_filt_init();
    }
    hook_logf("=== push_hook loaded: pid=%d uid=%d comm=%s active=%d bulk=%p submit=%p shm=%p seq_input=%p ===\n",
         (int)getpid(), (int)getuid(), comm, hook_active,
         (void *)real_bulk, (void *)real_submit, (void *)shm, (void *)real_seq_input);
}

/* ── Hook: snd_seq_event_input (ALSA sequencer — intercept MIDI to Live) ─── */

int snd_seq_event_input(void *seq, void **ev) {
    if (!real_seq_input) {
        real_seq_input = (seq_event_input_fn)dlsym(RTLD_NEXT, "snd_seq_event_input");
        if (!real_seq_input) return -1;
    }

    int ret = real_seq_input(seq, ev);
    if (!hook_active) return ret;
    if (ret < 0 || !ev || !*ev) return ret;
    if (!midi_filt || !midi_filt->enabled) return ret;

    /* snd_seq_event_t: type byte is at offset 0 */
    uint8_t *type_ptr = (uint8_t *)*ev;
    switch (type_ptr[0]) {
    case  6: /* SND_SEQ_EVENT_NOTE      */
    case  7: /* SND_SEQ_EVENT_NOTEON    */
    case  8: /* SND_SEQ_EVENT_NOTEOFF   */
    case  9: /* SND_SEQ_EVENT_KEYPRESS  */
    case 10: /* SND_SEQ_EVENT_CONTROLLER */
    case 11: /* SND_SEQ_EVENT_PGMCHANGE  */
    case 12: /* SND_SEQ_EVENT_CHANPRESS  */
    case 13: /* SND_SEQ_EVENT_PITCHBEND  */
        type_ptr[0] = 0; /* SND_SEQ_EVENT_NONE — RtMidi skips type-0 events */
        break;
    default:
        break; /* SysEx, Active Sensing, clock, etc. always pass through */
    }
    return ret;
}

/* ── Phase 2a: bar overlay ──────────────────────────────────────────────── */

static void overlay_bar(unsigned char *buf, int len, int pixel_offset) {
    const int bar_byte_start = BAR_Y * BYTES_PER_ROW;
    const int bar_byte_end   = (BAR_Y + BAR_H) * BYTES_PER_ROW;
    int chunk_start = pixel_offset;
    int chunk_end   = pixel_offset + len;
    int paint_start = bar_byte_start > chunk_start ? bar_byte_start : chunk_start;
    int paint_end   = bar_byte_end   < chunk_end   ? bar_byte_end   : chunk_end;
    if (paint_start >= paint_end) return;
    int lo = paint_start - chunk_start;
    int hi = paint_end   - chunk_start;
    if (lo & 1) lo++;
    if (hi & 1) hi--;
    if (lo >= hi) return;
    for (int i = lo; i < hi; i += 2) {
        int abs = pixel_offset + i;
        buf[i]   = BAR_COLOR_LO ^ XOR_PATTERN[abs & 3];
        buf[i+1] = BAR_COLOR_HI ^ XOR_PATTERN[(abs + 1) & 3];
    }
}

/* ── Phase 2b: full frame takeover ─────────────────────────────────────── */

static void takeover_frame(unsigned char *buf, int len, int pixel_offset) {
    if (!shm) return;
    int src_start = pixel_offset;
    int copy_len  = len;
    if (src_start >= TOTAL_BYTES) return;
    if (src_start + copy_len > TOTAL_BYTES) copy_len = TOTAL_BYTES - src_start;
    const uint8_t *src = shm->pixels + src_start;
    for (int i = 0; i < copy_len; i++) {
        int abs = src_start + i;
        buf[i] = src[i] ^ XOR_PATTERN[abs & 3];
    }
}

/* ── Display frame processing (logging + overlay) ───────────────────────── */

static void process_display_out(unsigned char *data, int length) {
    int n;
    uint32_t cur_mode;

    pthread_mutex_lock(&display_mutex);

    if (length == 16 &&
        data[0] == 0xFF && data[1] == 0xCC &&
        data[2] == 0xAA && data[3] == 0x88) {
        /* Frame header: reset pixel offset */
        pixel_byte_offset = 0;
        in_pixel_frame    = 1;
    } else if (in_pixel_frame && length > 16) {
        /* Pixel data chunk */
        cur_mode = shm ? shm->mode : DISPLAY_MODE_PASS;
        /* Boot grace: force passthrough during Push3's USB/hub bring-up window,
         * even if push-manager set a takeover mode early. No buffer mutation. */
        if (load_time && (time(NULL) - load_time) < BOOT_GRACE_SECS)
            cur_mode = DISPLAY_MODE_PASS;
        switch (cur_mode) {
        case DISPLAY_MODE_BAR:
            overlay_bar(data, length, pixel_byte_offset);
            break;
        case DISPLAY_MODE_TAKEOVER:
            takeover_frame(data, length, pixel_byte_offset);
            break;
        default:
            break; /* DISPLAY_MODE_PASS: do nothing */
        }
        pixel_byte_offset += length;
    } else {
        in_pixel_frame = 0;
    }

    n = display_frames++;
    pthread_mutex_unlock(&display_mutex);

    /* Logging: first 10 frames + every 300 */
    if (n > 10 && n % 300 != 0) return;

    char hdr[64] = {0};
    int hlen = length < 16 ? length : 16;
    int pos = 0;
    for (int i = 0; i < hlen; i++)
        pos += snprintf(hdr + pos, sizeof(hdr) - pos, "%02x ", data[i]);

    hook_logf("DISPLAY ep=0x01 OUT len=%-7d frame=%-5d offset=%-8d mode=%u header=[%s]\n",
         length, n, pixel_byte_offset,
         shm ? shm->mode : 99u, hdr);
}

/* ── Hook: libusb_bulk_transfer ─────────────────────────────────────────── */

int libusb_bulk_transfer(
    libusb_device_handle *dev_handle,
    unsigned char         endpoint,
    unsigned char        *data,
    int                   length,
    int                  *actual_length,
    unsigned int          timeout)
{
    if (!real_bulk) {
        real_bulk = (bulk_xfer_fn)dlsym(RTLD_NEXT, "libusb_bulk_transfer");
        if (!real_bulk) {
            void *lib = dlopen("/opt/push3/lib/libusb-1.0.so", RTLD_NOW | RTLD_GLOBAL);
            if (lib) real_bulk = (bulk_xfer_fn)dlsym(lib, "libusb_bulk_transfer");
        }
        if (!real_bulk) return -99;
    }

    /* Pass straight through in non-Push3 processes — no logging, no overlay. */
    if (!hook_active)
        return real_bulk(dev_handle, endpoint, data, length, actual_length, timeout);

    if (data && length > 0) {
        switch (endpoint) {
        case 0x01:
            process_display_out(data, length);
            break;
        case 0x83:
            if (midi_in_msgs < 50) {
                midi_in_msgs++;
                hook_logf("MIDI    ep=0x83 IN  len=%-4d data=[%02x %02x %02x %02x]\n", length,
                    length>0?data[0]:0, length>1?data[1]:0, length>2?data[2]:0, length>3?data[3]:0);
            }
            break;
        case 0x03:
            if (midi_out_msgs < 50) {
                midi_out_msgs++;
                hook_logf("MIDI    ep=0x03 OUT len=%-4d data=[%02x %02x %02x %02x]\n", length,
                    length>0?data[0]:0, length>1?data[1]:0, length>2?data[2]:0, length>3?data[3]:0);
            }
            break;
        case 0x84:
        case 0x04:
            if (display_frames < 5)
                hook_logf("VENDOR  ep=0x%02x    len=%-4d data=[%02x %02x %02x %02x]\n", endpoint, length,
                    length>0?data[0]:0, length>1?data[1]:0, length>2?data[2]:0, length>3?data[3]:0);
            break;
        }
    }

    return real_bulk(dev_handle, endpoint, data, length, actual_length, timeout);
}

/* ── Hook: libusb_submit_transfer (async path) ──────────────────────────── */

int libusb_submit_transfer(struct libusb_transfer *transfer) {
    if (!real_submit) {
        real_submit = (submit_xfer_fn)dlsym(RTLD_NEXT, "libusb_submit_transfer");
        if (!real_submit) {
            void *lib = dlopen("/opt/push3/lib/libusb-1.0.so", RTLD_NOW | RTLD_GLOBAL);
            if (lib) real_submit = (submit_xfer_fn)dlsym(lib, "libusb_submit_transfer");
        }
        if (!real_submit) return -99;
    }

    /* Pass straight through in non-Push3 processes. */
    if (!hook_active)
        return real_submit(transfer);

    if (transfer && transfer->buffer && transfer->length > 0) {
        unsigned char  ep   = transfer->endpoint;
        int            len  = transfer->length;
        unsigned char *data = transfer->buffer;

        switch (ep) {
        case 0x01:
            process_display_out(data, len);
            break;
        case 0x83:
            if (midi_in_msgs < 50) {
                midi_in_msgs++;
                hook_logf("MIDI(async) ep=0x83 IN  len=%-4d data=[%02x %02x %02x %02x]\n", len,
                    len>0?data[0]:0, len>1?data[1]:0, len>2?data[2]:0, len>3?data[3]:0);
            }
            break;
        case 0x03:
            if (midi_out_msgs < 50) {
                midi_out_msgs++;
                hook_logf("MIDI(async) ep=0x03 OUT len=%-4d data=[%02x %02x %02x %02x]\n", len,
                    len>0?data[0]:0, len>1?data[1]:0, len>2?data[2]:0, len>3?data[3]:0);
            }
            break;
        }
    }

    return real_submit(transfer);
}
