// gen_splash — renders a text string to a BGR565 Push 3 display frame and
// emits it as a C header (src/splash_data.h) for inclusion in push_hook.c.
//
// Run from the push-display directory:
//
//	go run gen_splash/main.go
//	# or, via Makefile: make splash
//
// Output: src/splash_data.h
//
// Rendering matches push-manager's renderOSDFrame: basicfont 7×13 at 2× scale,
// white on black, horizontally and vertically centered on a 960×160 canvas,
// BGR565 LE, stride 1024 px/row, frame duplicated (Push 3 sends frame twice).
package main

import (
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"os"

	"golang.org/x/image/font"
	"golang.org/x/image/font/basicfont"
	"golang.org/x/image/math/fixed"
)

// Display geometry — must match push_hook.c and display.go.
const (
	dispVisW   = 960
	dispH      = 160
	dispStride = 1024
	dispFrameB = dispStride * dispH * 2 // 327680 bytes per frame half
	dispBytes  = dispFrameB * 2         // 655360 bytes total (frame sent twice)
)

func renderSplash(text string) []byte {
	const scale = 2
	face := basicfont.Face7x13

	bounds, _ := font.BoundString(face, text)
	smallW := (-bounds.Min.X + bounds.Max.X).Round()
	smallH := (-bounds.Min.Y + bounds.Max.Y).Round()
	if smallW <= 0 || smallH <= 0 {
		return make([]byte, dispBytes)
	}

	// Render at 1× on a small canvas.
	small := image.NewNRGBA(image.Rect(0, 0, smallW, smallH))
	draw.Draw(small, small.Bounds(), image.Black, image.Point{}, draw.Src)
	d := font.Drawer{
		Dst:  small,
		Src:  image.White,
		Face: face,
		Dot:  fixed.Point26_6{X: -bounds.Min.X, Y: -bounds.Min.Y},
	}
	d.DrawString(text)

	// Scale 2× and center on 960×160 canvas.
	scaledW := smallW * scale
	scaledH := smallH * scale
	startX := (dispVisW - scaledW) / 2
	startY := (dispH - scaledH) / 2

	canvas := image.NewNRGBA(image.Rect(0, 0, dispVisW, dispH))
	for sy := 0; sy < smallH; sy++ {
		for sx := 0; sx < smallW; sx++ {
			c := small.At(sx, sy)
			r, g, b, a := c.RGBA()
			if a == 0 {
				continue
			}
			pix := color.NRGBA{R: uint8(r >> 8), G: uint8(g >> 8), B: uint8(b >> 8), A: uint8(a >> 8)}
			for dy := 0; dy < scale; dy++ {
				for dx := 0; dx < scale; dx++ {
					px := startX + sx*scale + dx
					py := startY + sy*scale + dy
					if px >= 0 && px < dispVisW && py >= 0 && py < dispH {
						canvas.SetNRGBA(px, py, pix)
					}
				}
			}
		}
	}

	// Convert canvas to BGR565 LE, stride 1024, duplicated into both frame halves.
	pixels := make([]byte, dispBytes)
	for y := 0; y < dispH; y++ {
		for x := 0; x < dispVisW; x++ {
			r16, g16, b16, _ := canvas.At(x, y).RGBA()
			b5 := uint16(b16 >> 11)
			g6 := uint16(g16 >> 10)
			r5 := uint16(r16 >> 11)
			v := (b5 << 11) | (g6 << 5) | r5
			off := (y*dispStride + x) * 2
			lo, hi := byte(v), byte(v>>8)
			pixels[off] = lo
			pixels[off+1] = hi
			pixels[dispFrameB+off] = lo
			pixels[dispFrameB+off+1] = hi
		}
	}
	return pixels
}

func main() {
	text := "Push Hack loaded..."
	if len(os.Args) > 1 {
		text = os.Args[1]
	}

	pixels := renderSplash(text)

	out := "src/splash_data.h"
	f, err := os.Create(out)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create %s: %v\n", out, err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintf(f, "/* splash_data.h — generated by gen_splash/main.go, do not edit\n")
	fmt.Fprintf(f, " * Text: %q\n", text)
	fmt.Fprintf(f, " * Rendering: basicfont 7x13 @ 2x scale, white on black, centered 960x160\n")
	fmt.Fprintf(f, " * Format: BGR565 LE, stride 1024 px/row, frame duplicated (655360 bytes)\n")
	fmt.Fprintf(f, " */\n")
	fmt.Fprintf(f, "#pragma once\n")
	fmt.Fprintf(f, "#include <stdint.h>\n\n")
	fmt.Fprintf(f, "#define SPLASH_PIXEL_BYTES %d\n\n", len(pixels))
	fmt.Fprintf(f, "static const uint8_t splash_pixels[SPLASH_PIXEL_BYTES] = {\n")

	for i, b := range pixels {
		if i%16 == 0 {
			fmt.Fprintf(f, "    ")
		}
		fmt.Fprintf(f, "0x%02X,", b)
		if i%16 == 15 {
			fmt.Fprintf(f, "\n")
		}
	}
	if len(pixels)%16 != 0 {
		fmt.Fprintf(f, "\n")
	}
	fmt.Fprintf(f, "};\n")

	fmt.Printf("Generated %s: %q (%d bytes, %d non-zero)\n", out, text, len(pixels), countNonZero(pixels))
}

func countNonZero(b []byte) int {
	n := 0
	for _, v := range b {
		if v != 0 {
			n++
		}
	}
	return n
}
